"""add chat_messages and cover_letter source

Revision ID: 164269e26927
Revises: c1e5b8f92a04
Create Date: 2026-07-06 14:42:35.355856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "164269e26927"
down_revision: Union[str, Sequence[str], None] = "c1e5b8f92a04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("produced_version", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_chat_messages_application_id_applications"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chat_messages_application_id"),
            ["application_id"],
            unique=False,
        )

    with op.batch_alter_table("cover_letters", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source", sa.String(), server_default="generated", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cover_letters", schema=None) as batch_op:
        batch_op.drop_column("source")

    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_messages_application_id"))

    op.drop_table("chat_messages")
    # ### end Alembic commands ###
